<a href="https://colab.research.google.com/github/19PA1A04D6/silver-doodle/blob/master/Numpy_exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>**Numpy Introduction**</center>
![alt text](https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png)

Numpy is a general-purpose array-processing package...
It provides 
* High performance multi-dimensional arry object....
*   Tools to work with these array objects.....
* Numpy operations are vectorized..



It is mainly used in scientific computing....
-----
Importing numpy package....

In [0]:
import numpy as np


# **Creating 1-D array**
* We can create array using lists,tuples as follows

In [4]:
# create a numpy array using list
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a.shape)

(2, 3)


In [6]:
print(a.size)

6


In [10]:
print(a.argmax())

5


In [17]:
a=np.array((7,8,9,4,5,6,1))
print(max(a))

9


In [18]:
a=np.arange(0,15,5)
print(a)

[ 0  5 10]


* Python lists are similar to Numpy Lists...
* Then What is the purpose of having numpy arrays....
![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRADkTaMgXw0kSz05Rh7hAaoyGcik9UvBwqYAAVIB9uGJlFlXkJ)

* Because numpy arrays are faster and takes less memory...

In [0]:
# let's see a program to know the storage of numpy arrays...
import sys
l1=list(range(1000))
a3=np.array(l1)
print("Amount of memory consumed by python list..",len(l1)*sys.getsizeof(l1[0]))
print("Amount of memory consumed by numpy array...",a3.size*a3.itemsize)

Amount of memory consumed by python list.. 24000
Amount of memory consumed by numpy array... 8000


In [0]:
# let's see another program to know about time consumed by numpy arrays....
import time
t1=time.time()
for j in range(len(l1)):
  l1[j]+=5
t2=time.time()
a3=a3+5
t3=time.time()
print("Time taken by the list l1 to add 5 to each element of list is...",(t2-t1)*100000)
print("Time taken by the numpy array to add 5 to each element of numpy array is...",(t3-t2)*100000)

Time taken by the list l1 to add 5 to each element of list is... 17.04692840576172
Time taken by the numpy array to add 5 to each element of numpy array is... 9.012222290039062


* This is why we use numpy for scientific computing...

#### We can also create 2-D arrays.... 

* We can also create n-d arrays using python lists and tuples...

In [0]:
# create a 2-d array using list


In [0]:
# we can also create n-d arrays with zeros using zeros method


In [0]:
# we can also create n-d arrays with ones using ones method


In [0]:
# create a 2-d array using tuples

### Let's explore more about numpy arrays...

In [0]:
# let's see the datatype of numpy arrays....


In [0]:
# shape or dimensions of numpy array


In [0]:
# size of numpu array


In [0]:
# maximum element...


### Generating numbers between a range with a specific difference
- using function arange

In [0]:
# create an array of numbers using arange method


### Generating **n** numbers between a range
- using function linspace

In [20]:
# use linspace method to create numpy array
a=np.linspace(0,5,3)
print(a)

[0.  2.5 5. ]


### Generating random sample of given dimensions
**Note - Random numbers are generated between 0 to 1. Multiply them with an appropriate factor to get required outcome.**

In [0]:
# creating numpy arrays of required dimensions with random numbers..


In [21]:
# What if we wnnt to create an array with random numbers between 1 to 100
a=np.random.random((4,4))
print(a)

[[0.43933331 0.29710066 0.19515014 0.14431307]
 [0.14889234 0.67888523 0.66435743 0.77418646]
 [0.43039481 0.74936409 0.08739927 0.28213378]
 [0.98644191 0.8936814  0.87248867 0.46593473]]


### Basic array operations
**Note - The operations are vectorised**


In [23]:
# let's create two numpy arrays 
a=np.array((1,2,3,4,5,6))
print(a)
b=np.array((7,8,9,4,5,6,))
print(b)

[1 2 3 4 5 6]
[7 8 9 4 5 6]


In [25]:
# we can do all arithmetic operations on numpy arrays with ease +,-,/,*,%
print(a+b)
print(a-b)
print(a%b)
print(a/b)
print(a//b)
print(a*b)

[ 8 10 12  8 10 12]
[-6 -6 -6  0  0  0]
[1 2 3 0 0 0]
[0.14285714 0.25       0.33333333 1.         1.         1.        ]
[0 0 0 1 1 1]
[ 7 16 27 16 25 36]


In [0]:
# Broadcasting or recycling...


In [0]:
# Boolean operations..


#### Matrix multiplication

In [0]:
# use matmul function


### Some array operations
- max, min, sum, cumsum, sqrt, log etc

### Subsetting slicing and indexing
* We can access the elements of numpy n-d arrays using indexing..
* We can use numbers,array of numbers, boolean arrays as indices

In [0]:
#let's create a 2-d array..


In [0]:
# let's see boolean array indexing


In [0]:
# let's see the magic of boolean indexing...


In [0]:
# slicing


**Remember slices of numpy array shares memory..**

<centre> ![alt text](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTPd1SAx9N15GzpLNBp5gN_aAucYdFvj3ic9BpZVR48QW6qVOTu)
## ***yeah!***